#include<bits/stdc++.h>
using namespace std;

// int main()
// {
//     int n,flag=0;

//     cin>>n;
//     if(n==1||n==2||n==3) flag=0;

//     else
//     {
//         for(int i=2;i<n;i++)
//         {
//             if(n%i==0)
//             {
//                 flag=1;
//                 break;
//             }   
//         }
//     }
//     if(flag==1) cout<<"Not prime number";
//     else cout<<"prime number";
// }


int main()
{
    unsigned long long int s;
    s=999999999999999999 * 10;
    cout<<s;
}
